using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;

namespace mesoBoard.Web.Helpers
{
    public static class UrlHelpers
    {
        public static string PluginContent(this IUrlHelper url, string contentPath)
        {
            string pluginFolder = (string)url.ActionContext.HttpContext.Items[HttpContextItemKeys.PluginFolder];

            if (string.IsNullOrWhiteSpace(pluginFolder))
                throw new InvalidOperationException("No plugin folder declared. 'PluginContent' must be called in side a view generated by a plugin controller action");

            return url.Content("~/Plugins/" + pluginFolder + "/" + contentPath);
        }

        public static string AdminContent(this IUrlHelper url, string contentPath)
        {
            return url.Content(System.IO.Path.Combine("~/Areas/Admin/Content", contentPath));
        }

        public static string ThemeImage(this IUrlHelper url, string imageFileName)
        {
            string themeName = url.ActionContext.HttpContext.Items[HttpContextItemKeys.ThemeFolder].ToString();

            return url.Content("~/Themes/" + themeName + "/Images/" + imageFileName);
        }

        public static string ThemeContent(this IUrlHelper url, string themeFolderRelativeContentPath)
        {
            string themeName = url.ActionContext.HttpContext.Items[HttpContextItemKeys.ThemeFolder].ToString();

            themeFolderRelativeContentPath = themeFolderRelativeContentPath.Replace("~/", "");

            return url.Content("~/Themes/" + themeName + "/" + themeFolderRelativeContentPath);
        }
    }
}