//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentID { get; set; }
        public int PostID { get; set; }
        public string DownloadName { get; set; }
        public string SavedName { get; set; }
        public string Type { get; set; }
        public int Size { get; set; }
        public int Downloaded { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
