//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public Forum()
        {
            this.ForumPermissions = new HashSet<ForumPermission>();
            this.Threads = new HashSet<Thread>();
        }
    
        public int ForumID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        public bool VisibleToGuests { get; set; }
        public bool AllowGuestDownloads { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ForumPermission> ForumPermissions { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
