//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumPermission
    {
        public int ForumPermissionID { get; set; }
        public int ForumID { get; set; }
        public int Visibility { get; set; }
        public int Posting { get; set; }
        public int Polling { get; set; }
        public int Attachments { get; set; }
        public int RoleID { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual Role Role { get; set; }
    }
}
