//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        public Poll()
        {
            this.PollOptions = new HashSet<PollOption>();
        }
    
        public int PollID { get; set; }
        public string Question { get; set; }
    
        public virtual ICollection<PollOption> PollOptions { get; set; }
        public virtual Thread Thread { get; set; }
    }
}
