//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public Rank()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int RankID { get; set; }
        public string Title { get; set; }
        public int PostCount { get; set; }
        public string Image { get; set; }
        public string Color { get; set; }
        public bool IsRoleRank { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
