//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        public Thread()
        {
            this.Posts = new HashSet<Post>();
            this.ThreadViews = new HashSet<ThreadView>();
            this.ThreadViewStamps = new HashSet<ThreadViewStamp>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int ThreadID { get; set; }
        public int ForumID { get; set; }
        public string Title { get; set; }
        public int Type { get; set; }
        public bool HasPoll { get; set; }
        public bool IsLocked { get; set; }
        public string Image { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual Poll Poll { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<ThreadView> ThreadViews { get; set; }
        public virtual ICollection<ThreadViewStamp> ThreadViewStamps { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
