//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;

    public partial class User
    {
        public User()
        {
            this.InRoles = new HashSet<InRole>();
            this.MessagesSent = new HashSet<Message>();
            this.MessagesReceived = new HashSet<Message>();
            this.PollVotes = new HashSet<PollVote>();
            this.Posts = new HashSet<Post>();
            this.ThreadViews = new HashSet<ThreadView>();
            this.ThreadViewStamps = new HashSet<ThreadViewStamp>();
            this.Subscriptions = new HashSet<Subscription>();
        }

        public int UserID { get; set; }

        public string Username { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public string PasswordSalt { get; set; }

        public string ActivationCode { get; set; }

        public bool Status { get; set; }

        public System.DateTime RegisterDate { get; set; }

        public string RegisterIP { get; set; }

        public System.DateTime LastLoginDate { get; set; }

        public string LastLoginIP { get; set; }

        public System.DateTime LastLogoutDate { get; set; }

        public Nullable<System.DateTime> LastPostDate { get; set; }

        public string UsernameLower { get; set; }

        public virtual ICollection<InRole> InRoles { get; set; }

        public virtual ICollection<Message> MessagesSent { get; set; }

        public virtual ICollection<Message> MessagesReceived { get; set; }

        public virtual OnlineUser OnlineUser { get; set; }

        public virtual PasswordResetRequest PasswordResetRequest { get; set; }

        public virtual ICollection<PollVote> PollVotes { get; set; }

        public virtual ICollection<Post> Posts { get; set; }

        public virtual ICollection<ThreadView> ThreadViews { get; set; }

        public virtual ICollection<ThreadViewStamp> ThreadViewStamps { get; set; }

        public virtual UserProfile UserProfile { get; set; }

        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}