//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mesoBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserID { get; set; }
        public bool AlwaysSubscribeToThread { get; set; }
        public bool AlwaysShowSignature { get; set; }
        public Nullable<int> ThemeID { get; set; }
        public string AvatarType { get; set; }
        public string Avatar { get; set; }
        public string Location { get; set; }
        public Nullable<int> DefaultRole { get; set; }
        public string AIM { get; set; }
        public Nullable<int> ICQ { get; set; }
        public string MSN { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Signature { get; set; }
        public string ParsedSignature { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual User User { get; set; }
    }
}
